### ISSUE TITLE
/etc/qbus/keys

### ISSUE THREAD

**Issue by tomplus** [qnap-dev/container-station-script#2]
https://github.com/qnap-dev/container-station-script/blob/88ebc288911c1fc700ffff40f41b01eeb196a3a3/debug.sh#L78

Directory `/etc/qbus/keys` contains a server cert and a private key. IMO it'd better if these files were excluded to avoid suspicious. Thanks.

**Comment by fcwu** [comment]
agree

**Comment by fcwu** [comment]
Close by b7b6bdd
